### ISSUE TITLE
Struggling to get your ruby gem to work... what am I doing wrong

### ISSUE THREAD

**Issue by zimpower** [alex-phillips/clouddrive#2]
Hi Alex,

Firstly thanks for writing this gem. I am a ruby hobbiest and was trying to write some ruby scripts to backup my photo collection to the amazon cloud in a smarter way than their current Mac App.

I have setup my security profile on the amazon developer console and I am using my amazon login email, the 'Client ID' and 'Client Secret' from it to initialise your Account class (shown below).

After installing the gem I tried your example script in irb also shown below but got an error message.

Am I missing an authorisation step?
Or should I redirected to a Safari page for button-cick authorisation?

Thanks in advance... 

![amazon_apps___services_developer_portal](https://cloud.githubusercontent.com/assets/3992242/9607615/14ab521c-50c2-11e5-80ef-b66f8e88ebbc.jpg)

![1__ruby](https://cloud.githubusercontent.com/assets/3992242/9608260/77067b32-50c5-11e5-8d89-ebfaea47dbec.jpg)

**Comment by alex-phillips** [comment]
Thanks for the interest in the project! I need to finish up the feature set, but what is there should be fully functional.

From looking at the screenshots and from what you're describing, it sounds like the authorization isn't getting completed. The way this works is the app generates that auth URL for you to hit and then you paste in the redirect URL. However, for this to properly work, the 'callback' URL has to be set up in your security profile to match what the auth URL is attempting to redirect to. This is currently non-configurable and set to "localhost".

So, I believe you simply need to set "http://localhost" as a valid callback URL in your amazon security profile. This can be done in the 'web settings' tab.

![image](https://cloud.githubusercontent.com/assets/3135216/9613346/c97b0dea-50b8-11e5-8ccf-84fcec56d889.png)

Let me know if this doesn't fix the issue.

**Comment by zimpower** [comment]
Thanks for the response.

I think my Web Settings are fine (shown at bottom) as localhost is on there.

I am trying to run this on my personal mac - is that ok, or should it be run as part of a web-app? Maybe I am missing the big picture...
-) I think there is one bug on line 55 where your auth_url scope should be: 
	"scope=clouddrive%3Aread_all”  i/o  "scope=clouddrive%3Aread"
-) For now - if I make “read” -> “read_all" change and then manually paste the “auth_url” returned from the first authorize into safari I then get an error:

-) If i pass the “localhost/?…write” string into my second account.authorize() call then I make more progress:
	=> {:success=>true, :data=>{}}

I guess the question is how (if possible) can I avoid manual safari steps.

Thanks

Simon

**Comment by alex-phillips** [comment]
Ah. Amazon recently changed their API 'scopes' from "read" to "read_all" and I haven't updated the repo since. I can make that change and push it up.

Your use of this is totally within scope. So if you make that "read_all" change, does the redirect URL come back with a code as a CGI param?

**Comment by zimpower** [comment]
Maybe i am doing it wrong. Current to make it work i go through the following steps:


In IRB:
1- require ‘clouddrive’
2- account = = CloudDrive::Account.new( … )
3- account.authorize()
4- I copy the returned auth_url into safari and see a page that looks like:
3- I click on the Amazon ‘Continue’ button :

5- Safari errors:

6- I copy the string “localhost/?….%3Awrite” shown in Safari and, in IRB, paste it into the second account.authorize(<paste here>) call
7- This works and I am good to go… with sync etc...

So it works but very manual. Is there anyway to skip the manual safari steps 4-… 6-?

**Comment by alex-phillips** [comment]
That sounds right. Unfortunately, since it's OAuth but only with an HTTP endpoint, it is a bit of a manual process. I left the classes open so someone could maybe build a better workaround, but I haven't been able to make a more seamless usage other than prompting the user in the command line for the redirect URL and passing the input into a second authorize method call.

However, once you are authorized, the access token should all be stored and you shouldn't have to do this again. It is a one-time authorization process FWIW. Does that make sense?

**Comment by alex-phillips** [comment]
If you can hang tight for a couple of days, I think I can refactor this to make a bit more sense (and be a bit more usable). Go ahead and run with the code I have now, but I'll be able to spend some time over the next couple of days and get this back up to par with its partner PHP repo (https://github.com/alex-phillips/clouddrive-php).

**Comment by zimpower** [comment]
Thanks - makes sense. I just wanted to check that I wasn’t missing something obvious. The PHP Readme is a lot more clear about the Web Browser approval step.

The whole process seems clunky but perhaps that is what Amazon wants. If they made this as simple/accessible as rsync then they’d get TBs of data sent to their cloud drives.

The other idea I had was to host your gem inside a web_app. EG a sinatra based for example could potentially launch the amazon login site and intercept the redirect_uri call.

Once again - thanks for putting this together. Appreciated.

**Comment by alex-phillips** [comment]
Thanks for the input! The problem with running a small webserver to launch and intercept the callback is that it would still require user interaction either for confirmation or for the user to login first and then confirm (I'm sure this is security for the user to make sure they want to actually allow the 'app' from accessing their data).

Any other ideas would be awesome if you come up with anything. And thanks for your interest in the project!

**Comment by zimpower** [comment]
Hi Alex,

I went away and tried to code the amazon API myself: I need to learn.
Then I compared my efforts to your gem unsurprisingly your code was much better in almost every way… but I do have a couple of  questions:

1- Most amazon API calls return response.code === 401 when the access_token needs refreshing.
     In my implementation I had some code patterns as follows 
     
     def amazon_file_upload(opts = {})
	# stuff 
	RestClient.post ( … ) do |response, request, result|
	if response.code === 201
		return JSON.parse(response.body)
	elsif response.code === 401
		refresh_access_token
		return amazon_file_upload(opts)   # => retry
        else
		# handle error
		return nil
        end
     end

So a lazy access_token refresh when required… avoids the need to actively refresh the token, cache expiry times etc… 

What do you think of this idea?

2- You code is tightly linked to sqlite… any reason for that choice?

3- One issue that caused me an hour of confusion is when you delete items on amazon they initially get put in a trash folder. That is fine so long as you aren’t using a localId when uploading as it will error trying to uploading/creating a node with the same localId, even if in a different Folder. Once you permanently delete the trash on Amazon then you are fine, but makes me wonder about the validity of using a localId...

Cheers

Simon

**Comment by alex-phillips** [comment]
Simon,

1. Your solution to fix the refresh seems valid. I will definitely implement this.
2. If you take a look at the PHP and NodeJS versions I've written, they are compatible with MySQL, SQLite3, Postgres, etc. I plan to make the same changes to the Ruby module as well.
3. I haven't implemented (in any of the projects) an localID at this point. I've found it difficult to be able to generate a localID that is completely unique to that file, but allow it to be generated the same on different computers. Any suggestions on this would be great.

I plan to do a major refactor of the Ruby module in the near future. Please stand by.

**Comment by alex-phillips** [comment]
Simon,

Regarding your upload solution. Be aware that if the upload fails with a 401, Amazon still probably made a node but gave it a PENDING status. What you'll want to do after the 401 is resync, and then upload the file with an overwrite flag. Otherwise, you'll upload the file a second time and you'll have 2 nodes existing: 1 (completed) with a status of AVAILABLE, and another of PENDING which you can never get rid of without resuming the upload by overwriting the node's contents.

**Comment by alex-phillips** [comment]
@zimpower, Check out the new `refactor` branch. Not all features are implemented yet, but progress is coming along quite nicely. I think you'll like the changes. Let me know what you think.
