### ISSUE TITLE
https://data-mind-687.appspot.com/clouddrive - returns 404

### ISSUE THREAD

**Issue by OskarStark** [alex-phillips/clouddrive#9]
Hi,

can you please check, why this url isn't available anymore?
https://data-mind-687.appspot.com/clouddrive

thank you!

**Comment by OskarStark** [comment]
does it belong to: https://github.com/alex-phillips/node-clouddrive/issues/47#issuecomment-305278656 ??

**Comment by alex-phillips** [comment]
@OskarStark Yes. Amazon has discontinued their v1 API in addition to the unlimited plan. So this project no longer works.

**Comment by OskarStark** [comment]
Thank you
